#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void vt_console_trigger_deliver 
    (__po_hi_request_t* request);

void* vt_console_trigger_job (void);

void vt_console_tm_deliver 
    (__po_hi_request_t* request);

void* vt_console_tm_job (void);

void vt_roberto_tc_deliver 
    (__po_hi_request_t* request);

void* vt_roberto_tc_job (void);

void vt_roberto_trigger_deliver 
    (__po_hi_request_t* request);

void* vt_roberto_trigger_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
