#include <types.h>
#include <deployment.h>
#include <po_hi_gqueue.h>
#include <po_hi_types.h>
#include <request.h>
#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object console_protected;
extern process_package__taste_protected_object roberto_protected;
__po_hi_port_t __po_hi_vt_console_trigger_outport_tc_vt_local_destinations[1] = {vt_roberto_tc_global_inport_artificial_tc};
__po_hi_port_id_t __po_hi_vt_console_trigger_woffsets[__po_hi_vt_console_trigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_console_trigger_offsets[__po_hi_vt_console_trigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_console_trigger_used_size[__po_hi_vt_console_trigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_console_trigger_empties[__po_hi_vt_console_trigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_console_trigger_first[__po_hi_vt_console_trigger_nb_ports];
__po_hi_request_t __po_hi_vt_console_trigger_recent[__po_hi_vt_console_trigger_nb_ports];
__po_hi_port_t __po_hi_vt_console_trigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_console_trigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_console_trigger_history[0];
__po_hi_port_id_t __po_hi_vt_console_trigger_n_dest[__po_hi_vt_console_trigger_nb_ports] = {1};
__po_hi_port_id_t __po_hi_vt_console_trigger_fifo_size[__po_hi_vt_console_trigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_console_trigger_destinations[__po_hi_vt_console_trigger_nb_ports] = {__po_hi_vt_console_trigger_outport_tc_vt_local_destinations};

/*!
 * \fn void* vt_console_trigger_job (void)
 * \brief Function executed by the task vt_console_trigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_console_trigger*/
extern void po_hi_c_vt_console_trigger_artificial_trigger 
    (__po_hi_task_id self);
void* vt_console_trigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_console_trigger_k, __po_hi_vt_console_trigger_nb_ports, __po_hi_vt_console_trigger_queue, __po_hi_vt_console_trigger_fifo_size, __po_hi_vt_console_trigger_first, __po_hi_vt_console_trigger_offsets, __po_hi_vt_console_trigger_woffsets, __po_hi_vt_console_trigger_n_dest, __po_hi_vt_console_trigger_destinations, __po_hi_vt_console_trigger_used_size, __po_hi_vt_console_trigger_history, __po_hi_vt_console_trigger_recent, __po_hi_vt_console_trigger_empties, __po_hi_vt_console_trigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_console_trigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_console_trigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_console_trigger_artificial_trigger (x86_partition_vt_console_trigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_console_trigger_k, vt_console_trigger_global_outport_tc_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_console_trigger_k);
  }
}

__po_hi_port_t __po_hi_vt_console_tm_outport_tc_vt_local_destinations[1] = {vt_roberto_tc_global_inport_artificial_tc};
__po_hi_port_id_t __po_hi_vt_console_tm_woffsets[__po_hi_vt_console_tm_nb_ports];
__po_hi_port_id_t __po_hi_vt_console_tm_offsets[__po_hi_vt_console_tm_nb_ports];
__po_hi_port_id_t __po_hi_vt_console_tm_used_size[__po_hi_vt_console_tm_nb_ports];
__po_hi_port_id_t __po_hi_vt_console_tm_empties[__po_hi_vt_console_tm_nb_ports];
__po_hi_port_id_t __po_hi_vt_console_tm_first[__po_hi_vt_console_tm_nb_ports];
__po_hi_request_t __po_hi_vt_console_tm_recent[__po_hi_vt_console_tm_nb_ports];
__po_hi_port_t __po_hi_vt_console_tm_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_console_tm_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_console_tm_history[1];
__po_hi_port_id_t __po_hi_vt_console_tm_n_dest[__po_hi_vt_console_tm_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_console_tm_fifo_size[__po_hi_vt_console_tm_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_console_tm_destinations[__po_hi_vt_console_tm_nb_ports] = {NULL,__po_hi_vt_console_tm_outport_tc_vt_local_destinations};

/*!
 * \fn void vt_console_tm_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_console_tm
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_console_tm_deliver) stores the incoming request for the 
 * taskvt_console_tm
 */
void vt_console_tm_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_console_tm_global_inport_artificial_tm:
    {
      __po_hi_gqueue_store_in (x86_partition_vt_console_tm_k, vt_console_tm_local_inport_artificial_tm, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_console_tm_job (void)
 * \brief Function executed by the task vt_console_tm
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_console_tm*/
extern void po_hi_c_vt_console_tm_artificial_tm 
    (__po_hi_task_id self,
    dataview__puspacket_buffer_impl inport_artificial_tm);
void* vt_console_tm_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_tm_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_console_tm_k, __po_hi_vt_console_tm_nb_ports, __po_hi_vt_console_tm_queue, __po_hi_vt_console_tm_fifo_size, __po_hi_vt_console_tm_first, __po_hi_vt_console_tm_offsets, __po_hi_vt_console_tm_woffsets, __po_hi_vt_console_tm_n_dest, __po_hi_vt_console_tm_destinations, __po_hi_vt_console_tm_used_size, __po_hi_vt_console_tm_history, __po_hi_vt_console_tm_recent, __po_hi_vt_console_tm_empties, __po_hi_vt_console_tm_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_vt_console_tm_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_vt_console_tm_k, &(port));
    __po_hi_compute_next_period (x86_partition_vt_console_tm_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_console_tm_local_inport_artificial_tm:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (x86_partition_vt_console_tm_k, vt_console_tm_local_inport_artificial_tm))
        {
                  __po_hi_gqueue_get_value (x86_partition_vt_console_tm_k, vt_console_tm_local_inport_artificial_tm, &(inport_artificial_tm_request));
          __po_hi_gqueue_next_value (x86_partition_vt_console_tm_k, vt_console_tm_local_inport_artificial_tm);

        }

        po_hi_c_vt_console_tm_artificial_tm (x86_partition_vt_console_tm_k, inport_artificial_tm_request.vars.vt_console_tm_global_inport_artificial_tm.vt_console_tm_global_inport_artificial_tm);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_console_tm_k, vt_console_tm_global_outport_tc_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_console_tm_k);
  }
}

__po_hi_port_t __po_hi_vt_roberto_tc_outport_tm_vt_local_destinations[1] = {vt_console_tm_global_inport_artificial_tm};
__po_hi_port_id_t __po_hi_vt_roberto_tc_woffsets[__po_hi_vt_roberto_tc_nb_ports];
__po_hi_port_id_t __po_hi_vt_roberto_tc_offsets[__po_hi_vt_roberto_tc_nb_ports];
__po_hi_port_id_t __po_hi_vt_roberto_tc_used_size[__po_hi_vt_roberto_tc_nb_ports];
__po_hi_port_id_t __po_hi_vt_roberto_tc_empties[__po_hi_vt_roberto_tc_nb_ports];
__po_hi_port_id_t __po_hi_vt_roberto_tc_first[__po_hi_vt_roberto_tc_nb_ports];
__po_hi_request_t __po_hi_vt_roberto_tc_recent[__po_hi_vt_roberto_tc_nb_ports];
__po_hi_port_t __po_hi_vt_roberto_tc_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_roberto_tc_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_roberto_tc_history[1];
__po_hi_port_id_t __po_hi_vt_roberto_tc_n_dest[__po_hi_vt_roberto_tc_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_roberto_tc_fifo_size[__po_hi_vt_roberto_tc_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_roberto_tc_destinations[__po_hi_vt_roberto_tc_nb_ports] = {NULL,__po_hi_vt_roberto_tc_outport_tm_vt_local_destinations};

/*!
 * \fn void vt_roberto_tc_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_roberto_tc
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_roberto_tc_deliver) stores the incoming request for the 
 * taskvt_roberto_tc
 */
void vt_roberto_tc_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_roberto_tc_global_inport_artificial_tc:
    {
      __po_hi_gqueue_store_in (x86_partition_vt_roberto_tc_k, vt_roberto_tc_local_inport_artificial_tc, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_roberto_tc_job (void)
 * \brief Function executed by the task vt_roberto_tc
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_roberto_tc*/
extern void po_hi_c_vt_roberto_tc_artificial_tc 
    (__po_hi_task_id self,
    dataview__puspacket_buffer_impl inport_artificial_tc);
void* vt_roberto_tc_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_tc_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_roberto_tc_k, __po_hi_vt_roberto_tc_nb_ports, __po_hi_vt_roberto_tc_queue, __po_hi_vt_roberto_tc_fifo_size, __po_hi_vt_roberto_tc_first, __po_hi_vt_roberto_tc_offsets, __po_hi_vt_roberto_tc_woffsets, __po_hi_vt_roberto_tc_n_dest, __po_hi_vt_roberto_tc_destinations, __po_hi_vt_roberto_tc_used_size, __po_hi_vt_roberto_tc_history, __po_hi_vt_roberto_tc_recent, __po_hi_vt_roberto_tc_empties, __po_hi_vt_roberto_tc_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_vt_roberto_tc_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_vt_roberto_tc_k, &(port));
    __po_hi_compute_next_period (x86_partition_vt_roberto_tc_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_roberto_tc_local_inport_artificial_tc:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (x86_partition_vt_roberto_tc_k, vt_roberto_tc_local_inport_artificial_tc))
        {
                  __po_hi_gqueue_get_value (x86_partition_vt_roberto_tc_k, vt_roberto_tc_local_inport_artificial_tc, &(inport_artificial_tc_request));
          __po_hi_gqueue_next_value (x86_partition_vt_roberto_tc_k, vt_roberto_tc_local_inport_artificial_tc);

        }

        po_hi_c_vt_roberto_tc_artificial_tc (x86_partition_vt_roberto_tc_k, inport_artificial_tc_request.vars.vt_roberto_tc_global_inport_artificial_tc.vt_roberto_tc_global_inport_artificial_tc);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_roberto_tc_k, vt_roberto_tc_global_outport_tm_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_roberto_tc_k);
  }
}

__po_hi_port_t __po_hi_vt_roberto_trigger_outport_tm_vt_local_destinations[1] = {vt_console_tm_global_inport_artificial_tm};
__po_hi_port_id_t __po_hi_vt_roberto_trigger_woffsets[__po_hi_vt_roberto_trigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_roberto_trigger_offsets[__po_hi_vt_roberto_trigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_roberto_trigger_used_size[__po_hi_vt_roberto_trigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_roberto_trigger_empties[__po_hi_vt_roberto_trigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_roberto_trigger_first[__po_hi_vt_roberto_trigger_nb_ports];
__po_hi_request_t __po_hi_vt_roberto_trigger_recent[__po_hi_vt_roberto_trigger_nb_ports];
__po_hi_port_t __po_hi_vt_roberto_trigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_roberto_trigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_roberto_trigger_history[0];
__po_hi_port_id_t __po_hi_vt_roberto_trigger_n_dest[__po_hi_vt_roberto_trigger_nb_ports] = {1};
__po_hi_port_id_t __po_hi_vt_roberto_trigger_fifo_size[__po_hi_vt_roberto_trigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_roberto_trigger_destinations[__po_hi_vt_roberto_trigger_nb_ports] = {__po_hi_vt_roberto_trigger_outport_tm_vt_local_destinations};

/*!
 * \fn void* vt_roberto_trigger_job (void)
 * \brief Function executed by the task vt_roberto_trigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_roberto_trigger*/
extern void po_hi_c_vt_roberto_trigger_artificial_trigger 
    (__po_hi_task_id self);
void* vt_roberto_trigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_roberto_trigger_k, __po_hi_vt_roberto_trigger_nb_ports, __po_hi_vt_roberto_trigger_queue, __po_hi_vt_roberto_trigger_fifo_size, __po_hi_vt_roberto_trigger_first, __po_hi_vt_roberto_trigger_offsets, __po_hi_vt_roberto_trigger_woffsets, __po_hi_vt_roberto_trigger_n_dest, __po_hi_vt_roberto_trigger_destinations, __po_hi_vt_roberto_trigger_used_size, __po_hi_vt_roberto_trigger_history, __po_hi_vt_roberto_trigger_recent, __po_hi_vt_roberto_trigger_empties, __po_hi_vt_roberto_trigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_roberto_trigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_roberto_trigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_roberto_trigger_artificial_trigger (x86_partition_vt_roberto_trigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_roberto_trigger_k, vt_roberto_trigger_global_outport_tm_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_roberto_trigger_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case x86_partition_vt_console_tm_k_entity:
    {
      vt_console_tm_deliver (request);

      break;
    }
    case x86_partition_vt_roberto_tc_k_entity:
    {
      vt_roberto_tc_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


