#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_taste_protected_object 
    (process_package__taste_protected_object value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (&(value), message, sizeof (process_package__taste_protected_object), offset);
}

void __po_hi_unmarshall_type_taste_protected_object 
    (process_package__taste_protected_object* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, sizeof (process_package__taste_protected_object), offset);
}

void __po_hi_marshall_type_puspacket_buffer_max_impl 
    (dataview__puspacket_buffer_max_impl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (value, message, 5784 * sizeof (dataview__stream_element_buffer), offset);
}

void __po_hi_unmarshall_type_puspacket_buffer_max_impl 
    (dataview__puspacket_buffer_max_impl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, 5784 * sizeof (dataview__stream_element_buffer), offset);
}

void __po_hi_marshall_type_stream_element_buffer 
    (dataview__stream_element_buffer value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_char (value, message, offset);
}

void __po_hi_unmarshall_type_stream_element_buffer 
    (dataview__stream_element_buffer* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_char (value, message, offset);
}

void __po_hi_marshall_type_unsigned_32 
    (base_types__unsigned_32 value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_uint32 (value, message, offset);
}

void __po_hi_unmarshall_type_unsigned_32 
    (base_types__unsigned_32* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_uint32 (value, message, offset);
}

void __po_hi_marshall_type_puspacket_buffer_impl 
    (dataview__puspacket_buffer_impl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_max_impl (value.buffer, message, offset);
  __po_hi_marshall_uint32 (value.length, message, offset);
}

void __po_hi_unmarshall_type_puspacket_buffer_impl 
    (dataview__puspacket_buffer_impl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_max_impl (&(value->buffer), message, offset);
  __po_hi_unmarshall_uint32 (&(value->length), message, offset);
}

void __po_hi_marshall_request_vt_console_trigger_outport_tc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_console_trigger_global_outport_tc_vt.vt_console_trigger_global_outport_tc_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_console_trigger_outport_tc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_console_trigger_global_outport_tc_vt.vt_console_trigger_global_outport_tc_vt), message, offset);
}

void __po_hi_marshall_request_vt_console_tm_inport_artificial_tm 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_console_tm_global_inport_artificial_tm.vt_console_tm_global_inport_artificial_tm, message, offset);
}

void __po_hi_unmarshall_request_vt_console_tm_inport_artificial_tm 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_console_tm_global_inport_artificial_tm.vt_console_tm_global_inport_artificial_tm), message, offset);
}

void __po_hi_marshall_request_vt_console_tm_outport_tc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_console_tm_global_outport_tc_vt.vt_console_tm_global_outport_tc_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_console_tm_outport_tc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_console_tm_global_outport_tc_vt.vt_console_tm_global_outport_tc_vt), message, offset);
}

void __po_hi_marshall_request_vt_roberto_tc_inport_artificial_tc 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_roberto_tc_global_inport_artificial_tc.vt_roberto_tc_global_inport_artificial_tc, message, offset);
}

void __po_hi_unmarshall_request_vt_roberto_tc_inport_artificial_tc 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_roberto_tc_global_inport_artificial_tc.vt_roberto_tc_global_inport_artificial_tc), message, offset);
}

void __po_hi_marshall_request_vt_roberto_tc_outport_tm_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_roberto_tc_global_outport_tm_vt.vt_roberto_tc_global_outport_tm_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_roberto_tc_outport_tm_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_roberto_tc_global_outport_tm_vt.vt_roberto_tc_global_outport_tm_vt), message, offset);
}

void __po_hi_marshall_request_vt_roberto_trigger_outport_tm_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_roberto_trigger_global_outport_tm_vt.vt_roberto_trigger_global_outport_tm_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_roberto_trigger_outport_tm_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_roberto_trigger_global_outport_tm_vt.vt_roberto_trigger_global_outport_tm_vt), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case vt_console_trigger_global_outport_tc_vt:
    {
      __po_hi_marshall_request_vt_console_trigger_outport_tc_vt (request, message, &(offset));

      break;
    }
    case vt_console_tm_global_inport_artificial_tm:
    {
      __po_hi_marshall_request_vt_console_tm_inport_artificial_tm (request, message, &(offset));

      break;
    }
    case vt_console_tm_global_outport_tc_vt:
    {
      __po_hi_marshall_request_vt_console_tm_outport_tc_vt (request, message, &(offset));

      break;
    }
    case vt_roberto_tc_global_inport_artificial_tc:
    {
      __po_hi_marshall_request_vt_roberto_tc_inport_artificial_tc (request, message, &(offset));

      break;
    }
    case vt_roberto_tc_global_outport_tm_vt:
    {
      __po_hi_marshall_request_vt_roberto_tc_outport_tm_vt (request, message, &(offset));

      break;
    }
    case vt_roberto_trigger_global_outport_tm_vt:
    {
      __po_hi_marshall_request_vt_roberto_trigger_outport_tm_vt (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case vt_console_trigger_global_outport_tc_vt:
    {
      __po_hi_unmarshall_request_vt_console_trigger_outport_tc_vt (request, message, &(offset));

      break;
    }
    case vt_console_tm_global_inport_artificial_tm:
    {
      __po_hi_unmarshall_request_vt_console_tm_inport_artificial_tm (request, message, &(offset));

      break;
    }
    case vt_console_tm_global_outport_tc_vt:
    {
      __po_hi_unmarshall_request_vt_console_tm_outport_tc_vt (request, message, &(offset));

      break;
    }
    case vt_roberto_tc_global_inport_artificial_tc:
    {
      __po_hi_unmarshall_request_vt_roberto_tc_inport_artificial_tc (request, message, &(offset));

      break;
    }
    case vt_roberto_tc_global_outport_tm_vt:
    {
      __po_hi_unmarshall_request_vt_roberto_tc_outport_tm_vt (request, message, &(offset));

      break;
    }
    case vt_roberto_trigger_global_outport_tm_vt:
    {
      __po_hi_unmarshall_request_vt_roberto_trigger_outport_tm_vt (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


