#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"vt_console_trigger_global_outport_tc_vt","vt_console_tm_global_inport_artificial_tm","vt_console_tm_global_outport_tc_vt","vt_roberto_tc_global_inport_artificial_tc","vt_roberto_tc_global_outport_tm_vt","vt_roberto_trigger_global_outport_tm_vt"};

