#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      dataview__puspacket_buffer_impl vt_console_trigger_global_outport_tc_vt;

    } vt_console_trigger_global_outport_tc_vt;

    struct
    {
      dataview__puspacket_buffer_impl vt_console_tm_global_inport_artificial_tm;

    } vt_console_tm_global_inport_artificial_tm;

    struct
    {
      dataview__puspacket_buffer_impl vt_console_tm_global_outport_tc_vt;

    } vt_console_tm_global_outport_tc_vt;

    struct
    {
      dataview__puspacket_buffer_impl vt_roberto_tc_global_inport_artificial_tc;

    } vt_roberto_tc_global_inport_artificial_tc;

    struct
    {
      dataview__puspacket_buffer_impl vt_roberto_tc_global_outport_tm_vt;

    } vt_roberto_tc_global_outport_tm_vt;

    struct
    {
      dataview__puspacket_buffer_impl vt_roberto_trigger_global_outport_tm_vt;

    } vt_roberto_trigger_global_outport_tm_vt;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
