all:
	sh cplibs.sh
	gcc -o prueba prueba.c -I/usr/include/python3.5m -lpython3.5m -I/home/esrocos/esrocos-ws-pus/pus/include/ -I/home/esrocos/esrocos-ws-pus/pus/debug/asn1/generated/ -I/home/esrocos/esrocos-ws-pus/pus/debug/mission/test_01/generated/include/ -Llibs -lesrocos_pus -lesrocos_pus_asn1 -lesrocos_pus_asn1common -lesrocos_pus_mission_test_01 -lpthread
