from PySide import QtGui

from Views.Views_Ui.Ui_MainView import Ui_MainView


class MainView:
    """
    This class represents a window. It references the class
    Ui_MainView, that class is where the graphical interface
    is created
    """

    def __init__(self):
        self.view = QtGui.QMainWindow()
        self.window = Ui_MainView()
        self.window.setupUi(self.view)
        self.extra_customization()
        self.window.centralwidget.resizeEvent = self.resize_elements

    def get_window(self):
        """
        This method returns the view that this class references

        :return: A view. It could be a QWidget, QMainWindow, etc.
        """
        return self.view

    def extra_customization(self):
        """
        This method allow us to define an extra configuration for the
        view without having to touch the code generated by the QtDesigner
        giving us a extra level of abstraction
        """
        header = self.window.packagesTable.horizontalHeader()
        header.setResizeMode(0, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(1, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(2, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(3, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(4, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(5, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(6, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(7, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(8, QtGui.QHeaderView.ResizeToContents)
        header.setResizeMode(9, QtGui.QHeaderView.ResizeToContents)
        self.window.packagesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.view.setStyleSheet("background-color: white")
        self.window.menubar.setStyleSheet("background: 3c3b37")
        self.window.label.setText(
            QtGui.QApplication.translate("MainView", "<html><head/><body><p>"
                                                     "<img src=\"Views/Views_Ui/images/logo_gmv.svg\""
                                                     "width=\"120\" height=\"67\"/></p></body></html>",
                                         None, QtGui.QApplication.UnicodeUTF8))
        header.sortIndicatorOrder()
        self.window.packagesTable.hideColumn(0)


    def resize_elements(self, event):
        """
        This method defines all the instructions needed to make
        our CreateTCView window responsive

        :param event: The event that triggers this method
        """
        padding = 10
        tw_w = self.window.packagesTable.frameGeometry().width()
        tw_h = self.window.packagesTable.frameGeometry().height()
        tw_x = self.window.packagesTable.pos().x()
        tw_y = self.window.packagesTable.pos().y()

        img_w = self.window.label.frameGeometry().width()
        img_h = self.window.label.frameGeometry().height()
        img_x = self.window.label.pos().x()
        img_y = self.window.label.pos().y()

        self.window.packagesTable.resize(self.window.centralwidget.frameGeometry().width() - img_w - padding,
                                         self.window.centralwidget.frameGeometry().height() - padding)
        self.window.label.move(self.window.packagesTable.frameGeometry().width()+padding, img_y)
